### ISSUE TITLE
estimated cost which are running in the project

### ISSUE THREAD

**Issue by vadirajks** [Cyclenerd/google-cloud-pricing-cost-calculator#185]
is this command going to get estimated cost of all the resource which are running in the project instead of providing everything in yaml input. I wanted to know price for each resource for on-demand, 1year,3 year commitments..etc for each resource to see how we can understand. Thanks

**Comment by Cyclenerd** [comment]
I'm not sure if I've understood you correctly, but this might help you: https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/tree/master/tools/asset
