### ISSUE TITLE
Yaml: unmarshal errors

### ISSUE THREAD

**Issue by logicvenu** [Cyclenerd/google-cloud-pricing-cost-calculator#194]
**Describe the bug**
I tried to run 'gcosts calc' and get the error. 'Yaml: unmarshal errors', enclosed error screenshot, I tried doing the YAML validation it didn't work. 

**To Reproduce**
1. Go to cmd prompt
2. type  gcosts calc

**Expected behavior**
Require the correct validated pricing .yml file to run gcosts calc.

**Screenshots**
![image](https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/assets/64354806/73873683-8bd3-4be8-9cce-3711f59f7d2b)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: chrome
 - Version 125.0.6422.61

**Additional context**

**Comment by Cyclenerd** [comment]
It looks to me as if the price list (`pricing.yml)` is in the same folder. Please see Warning and info message in Error.

**Comment by logicvenu** [comment]
As suggested, I did placed pricing.yml file in the separate folder (C:\Users\venug\Costs\Files\) and tried,

gcosts calc --dir C:\Users\venug\Costs --pricing C:\Users\venug\Costs\Files\

![image](https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/assets/64354806/ea856fee-3042-4771-b2e1-5f217487b0ce)

Please let me know what needs to be done.

**Comment by Cyclenerd** [comment]
The parameter `--pricing` must specify the file with the pricing and not the folder. Please also see the README: https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator?tab=readme-ov-file#3-run-it

**Comment by logicvenu** [comment]
gcosts region
gcosts region dual
gcosts region multi

Above stuff all works,
But when I run gcosts calc --dir C:\Users\venug\Costs --pricing C:\Users\venug\Costs\Files\pricing.yml 
I get Error: unmarshal errors

<img width="798" alt="image" src="https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/assets/64354806/7a8beb01-75f2-4f13-aea0-934b3313a133">

C:\Users\venug\Costs\Files

<img width="406" alt="image" src="https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/assets/64354806/49d99b81-79ec-470a-a6e8-baa1623026c2">

C:\Users\venug\Costs\usage
<img width="474" alt="image" src="https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/assets/64354806/1cd337a0-cfc8-48c6-a0e9-88078d68f553">

C:\Users\venug\Costs
<img width="402" alt="image" src="https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/assets/64354806/7590da47-fb39-4258-98a2-04079eefe8cb">

Have shared the directory structure for your review. Appreciate your help.

**Comment by logicvenu** [comment]
At last I was able to overcome the error "unmarshal errors".

gcosts calc --dir C:\Users\venug\Costs --pricing C:\Users\venug\Costs\Files\pricing.yml
<img width="770" alt="image" src="https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/assets/64354806/b2eb16a3-bc6b-49c6-98dd-d1ac41f587fc">

Created the excel file with no information.

Also when I executed gcosts region,  I get the error.
<img width="679" alt="image" src="https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/assets/64354806/7a0c4a44-2c5e-4878-b3dd-c7082a901447">
[costs.csv](https://github.com/user-attachments/files/15510901/costs.csv)

**Comment by Cyclenerd** [comment]
The error message indicates that the `pricing.yml` file is not at the specified location.
