### ISSUE TITLE
Bug: yaml: unmarshal errors:

### ISSUE THREAD

**Issue by cki-gh-mateusz-mazur** [Cyclenerd/google-cloud-pricing-cost-calculator#75]
**Describe the bug**
Running gcost on MacOS Ventura 13.3.1 and ubuntu server 22.04 (fresh installation) in basic example configuration returns error:

  ERROR   yaml: unmarshal errors:
            line 53142: cannot unmarshal !!map into []usage.Monitoring
            line 53377: cannot unmarshal !!map into string

App itsefl is newest version
**To Reproduce**
1. ./gcosts calc

**Expected behavior**
Calc working

**Comment by Cyclenerd** [comment]
I am not sure if it is a bug or wrong Usage YAML format. Please provide the YAML file.

**Comment by cki-gh-mateusz-mazur** [comment]
I have taken yaml file from examples. Here is the one Im using:

`region: europe-west4
project: my-first-project
instances:
  - name: app-server
    type: e2-standard-8
    os: rhel
    commitment: 3
    disks:
      - name: disk-boot
        type: ssd
        data: 75`

**Comment by Cyclenerd** [comment]
https://github.com/Cyclenerd/google-cloud-pricing-cost-calculator/commit/42db52f742a1607c64d0df4022eca4b3b1cfd91d

**Comment by cki-gh-mateusz-mazur** [comment]
@Cyclenerd Thank you! This fixed the issue :)
